# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikifri_niki/CalculateDragAndDrop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikifri_niki/CalculateDragAndDrop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikifri_niki/CalculateDragAndDrop/CMakeFiles /home/nikifri_niki/CalculateDragAndDrop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikifri_niki/CalculateDragAndDrop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CalculateDragAndDrop

# Build rule for target.
CalculateDragAndDrop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CalculateDragAndDrop
.PHONY : CalculateDragAndDrop

# fast build rule for target.
CalculateDragAndDrop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/build
.PHONY : CalculateDragAndDrop/fast

#=============================================================================
# Target rules for targets named CalculateDragAndDrop_autogen_timestamp_deps

# Build rule for target.
CalculateDragAndDrop_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CalculateDragAndDrop_autogen_timestamp_deps
.PHONY : CalculateDragAndDrop_autogen_timestamp_deps

# fast build rule for target.
CalculateDragAndDrop_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop_autogen_timestamp_deps.dir/build.make CMakeFiles/CalculateDragAndDrop_autogen_timestamp_deps.dir/build
.PHONY : CalculateDragAndDrop_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named CalculateDragAndDrop_autogen

# Build rule for target.
CalculateDragAndDrop_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CalculateDragAndDrop_autogen
.PHONY : CalculateDragAndDrop_autogen

# fast build rule for target.
CalculateDragAndDrop_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop_autogen.dir/build.make CMakeFiles/CalculateDragAndDrop_autogen.dir/build
.PHONY : CalculateDragAndDrop_autogen/fast

CalculateDragAndDrop_autogen/mocs_compilation.o: CalculateDragAndDrop_autogen/mocs_compilation.cpp.o
.PHONY : CalculateDragAndDrop_autogen/mocs_compilation.o

# target to build an object file
CalculateDragAndDrop_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/CalculateDragAndDrop_autogen/mocs_compilation.cpp.o
.PHONY : CalculateDragAndDrop_autogen/mocs_compilation.cpp.o

CalculateDragAndDrop_autogen/mocs_compilation.i: CalculateDragAndDrop_autogen/mocs_compilation.cpp.i
.PHONY : CalculateDragAndDrop_autogen/mocs_compilation.i

# target to preprocess a source file
CalculateDragAndDrop_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/CalculateDragAndDrop_autogen/mocs_compilation.cpp.i
.PHONY : CalculateDragAndDrop_autogen/mocs_compilation.cpp.i

CalculateDragAndDrop_autogen/mocs_compilation.s: CalculateDragAndDrop_autogen/mocs_compilation.cpp.s
.PHONY : CalculateDragAndDrop_autogen/mocs_compilation.s

# target to generate assembly for a file
CalculateDragAndDrop_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/CalculateDragAndDrop_autogen/mocs_compilation.cpp.s
.PHONY : CalculateDragAndDrop_autogen/mocs_compilation.cpp.s

srv/UI/Application/Application.o: srv/UI/Application/Application.cpp.o
.PHONY : srv/UI/Application/Application.o

# target to build an object file
srv/UI/Application/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Application/Application.cpp.o
.PHONY : srv/UI/Application/Application.cpp.o

srv/UI/Application/Application.i: srv/UI/Application/Application.cpp.i
.PHONY : srv/UI/Application/Application.i

# target to preprocess a source file
srv/UI/Application/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Application/Application.cpp.i
.PHONY : srv/UI/Application/Application.cpp.i

srv/UI/Application/Application.s: srv/UI/Application/Application.cpp.s
.PHONY : srv/UI/Application/Application.s

# target to generate assembly for a file
srv/UI/Application/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Application/Application.cpp.s
.PHONY : srv/UI/Application/Application.cpp.s

srv/UI/Button/Button.o: srv/UI/Button/Button.cpp.o
.PHONY : srv/UI/Button/Button.o

# target to build an object file
srv/UI/Button/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Button/Button.cpp.o
.PHONY : srv/UI/Button/Button.cpp.o

srv/UI/Button/Button.i: srv/UI/Button/Button.cpp.i
.PHONY : srv/UI/Button/Button.i

# target to preprocess a source file
srv/UI/Button/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Button/Button.cpp.i
.PHONY : srv/UI/Button/Button.cpp.i

srv/UI/Button/Button.s: srv/UI/Button/Button.cpp.s
.PHONY : srv/UI/Button/Button.s

# target to generate assembly for a file
srv/UI/Button/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Button/Button.cpp.s
.PHONY : srv/UI/Button/Button.cpp.s

srv/UI/CreateHistory/CreateHistory.o: srv/UI/CreateHistory/CreateHistory.cpp.o
.PHONY : srv/UI/CreateHistory/CreateHistory.o

# target to build an object file
srv/UI/CreateHistory/CreateHistory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/CreateHistory/CreateHistory.cpp.o
.PHONY : srv/UI/CreateHistory/CreateHistory.cpp.o

srv/UI/CreateHistory/CreateHistory.i: srv/UI/CreateHistory/CreateHistory.cpp.i
.PHONY : srv/UI/CreateHistory/CreateHistory.i

# target to preprocess a source file
srv/UI/CreateHistory/CreateHistory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/CreateHistory/CreateHistory.cpp.i
.PHONY : srv/UI/CreateHistory/CreateHistory.cpp.i

srv/UI/CreateHistory/CreateHistory.s: srv/UI/CreateHistory/CreateHistory.cpp.s
.PHONY : srv/UI/CreateHistory/CreateHistory.s

# target to generate assembly for a file
srv/UI/CreateHistory/CreateHistory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/CreateHistory/CreateHistory.cpp.s
.PHONY : srv/UI/CreateHistory/CreateHistory.cpp.s

srv/UI/Window/Window.o: srv/UI/Window/Window.cpp.o
.PHONY : srv/UI/Window/Window.o

# target to build an object file
srv/UI/Window/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Window/Window.cpp.o
.PHONY : srv/UI/Window/Window.cpp.o

srv/UI/Window/Window.i: srv/UI/Window/Window.cpp.i
.PHONY : srv/UI/Window/Window.i

# target to preprocess a source file
srv/UI/Window/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Window/Window.cpp.i
.PHONY : srv/UI/Window/Window.cpp.i

srv/UI/Window/Window.s: srv/UI/Window/Window.cpp.s
.PHONY : srv/UI/Window/Window.s

# target to generate assembly for a file
srv/UI/Window/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/UI/Window/Window.cpp.s
.PHONY : srv/UI/Window/Window.cpp.s

srv/main.o: srv/main.cpp.o
.PHONY : srv/main.o

# target to build an object file
srv/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/main.cpp.o
.PHONY : srv/main.cpp.o

srv/main.i: srv/main.cpp.i
.PHONY : srv/main.i

# target to preprocess a source file
srv/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/main.cpp.i
.PHONY : srv/main.cpp.i

srv/main.s: srv/main.cpp.s
.PHONY : srv/main.s

# target to generate assembly for a file
srv/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/main.cpp.s
.PHONY : srv/main.cpp.s

srv/test_f/alphaslider.o: srv/test_f/alphaslider.cpp.o
.PHONY : srv/test_f/alphaslider.o

# target to build an object file
srv/test_f/alphaslider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/alphaslider.cpp.o
.PHONY : srv/test_f/alphaslider.cpp.o

srv/test_f/alphaslider.i: srv/test_f/alphaslider.cpp.i
.PHONY : srv/test_f/alphaslider.i

# target to preprocess a source file
srv/test_f/alphaslider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/alphaslider.cpp.i
.PHONY : srv/test_f/alphaslider.cpp.i

srv/test_f/alphaslider.s: srv/test_f/alphaslider.cpp.s
.PHONY : srv/test_f/alphaslider.s

# target to generate assembly for a file
srv/test_f/alphaslider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/alphaslider.cpp.s
.PHONY : srv/test_f/alphaslider.cpp.s

srv/test_f/colorpicker.o: srv/test_f/colorpicker.cpp.o
.PHONY : srv/test_f/colorpicker.o

# target to build an object file
srv/test_f/colorpicker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/colorpicker.cpp.o
.PHONY : srv/test_f/colorpicker.cpp.o

srv/test_f/colorpicker.i: srv/test_f/colorpicker.cpp.i
.PHONY : srv/test_f/colorpicker.i

# target to preprocess a source file
srv/test_f/colorpicker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/colorpicker.cpp.i
.PHONY : srv/test_f/colorpicker.cpp.i

srv/test_f/colorpicker.s: srv/test_f/colorpicker.cpp.s
.PHONY : srv/test_f/colorpicker.s

# target to generate assembly for a file
srv/test_f/colorpicker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/colorpicker.cpp.s
.PHONY : srv/test_f/colorpicker.cpp.s

srv/test_f/hueslider.o: srv/test_f/hueslider.cpp.o
.PHONY : srv/test_f/hueslider.o

# target to build an object file
srv/test_f/hueslider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/hueslider.cpp.o
.PHONY : srv/test_f/hueslider.cpp.o

srv/test_f/hueslider.i: srv/test_f/hueslider.cpp.i
.PHONY : srv/test_f/hueslider.i

# target to preprocess a source file
srv/test_f/hueslider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/hueslider.cpp.i
.PHONY : srv/test_f/hueslider.cpp.i

srv/test_f/hueslider.s: srv/test_f/hueslider.cpp.s
.PHONY : srv/test_f/hueslider.s

# target to generate assembly for a file
srv/test_f/hueslider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/hueslider.cpp.s
.PHONY : srv/test_f/hueslider.cpp.s

srv/test_f/main.o: srv/test_f/main.cpp.o
.PHONY : srv/test_f/main.o

# target to build an object file
srv/test_f/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/main.cpp.o
.PHONY : srv/test_f/main.cpp.o

srv/test_f/main.i: srv/test_f/main.cpp.i
.PHONY : srv/test_f/main.i

# target to preprocess a source file
srv/test_f/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/main.cpp.i
.PHONY : srv/test_f/main.cpp.i

srv/test_f/main.s: srv/test_f/main.cpp.s
.PHONY : srv/test_f/main.s

# target to generate assembly for a file
srv/test_f/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_f/main.cpp.s
.PHONY : srv/test_f/main.cpp.s

srv/test_g/gradientSettings.o: srv/test_g/gradientSettings.cpp.o
.PHONY : srv/test_g/gradientSettings.o

# target to build an object file
srv/test_g/gradientSettings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradientSettings.cpp.o
.PHONY : srv/test_g/gradientSettings.cpp.o

srv/test_g/gradientSettings.i: srv/test_g/gradientSettings.cpp.i
.PHONY : srv/test_g/gradientSettings.i

# target to preprocess a source file
srv/test_g/gradientSettings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradientSettings.cpp.i
.PHONY : srv/test_g/gradientSettings.cpp.i

srv/test_g/gradientSettings.s: srv/test_g/gradientSettings.cpp.s
.PHONY : srv/test_g/gradientSettings.s

# target to generate assembly for a file
srv/test_g/gradientSettings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradientSettings.cpp.s
.PHONY : srv/test_g/gradientSettings.cpp.s

srv/test_g/gradient_editor.o: srv/test_g/gradient_editor.cpp.o
.PHONY : srv/test_g/gradient_editor.o

# target to build an object file
srv/test_g/gradient_editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradient_editor.cpp.o
.PHONY : srv/test_g/gradient_editor.cpp.o

srv/test_g/gradient_editor.i: srv/test_g/gradient_editor.cpp.i
.PHONY : srv/test_g/gradient_editor.i

# target to preprocess a source file
srv/test_g/gradient_editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradient_editor.cpp.i
.PHONY : srv/test_g/gradient_editor.cpp.i

srv/test_g/gradient_editor.s: srv/test_g/gradient_editor.cpp.s
.PHONY : srv/test_g/gradient_editor.s

# target to generate assembly for a file
srv/test_g/gradient_editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradient_editor.cpp.s
.PHONY : srv/test_g/gradient_editor.cpp.s

srv/test_g/gradient_strip.o: srv/test_g/gradient_strip.cpp.o
.PHONY : srv/test_g/gradient_strip.o

# target to build an object file
srv/test_g/gradient_strip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradient_strip.cpp.o
.PHONY : srv/test_g/gradient_strip.cpp.o

srv/test_g/gradient_strip.i: srv/test_g/gradient_strip.cpp.i
.PHONY : srv/test_g/gradient_strip.i

# target to preprocess a source file
srv/test_g/gradient_strip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradient_strip.cpp.i
.PHONY : srv/test_g/gradient_strip.cpp.i

srv/test_g/gradient_strip.s: srv/test_g/gradient_strip.cpp.s
.PHONY : srv/test_g/gradient_strip.s

# target to generate assembly for a file
srv/test_g/gradient_strip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/gradient_strip.cpp.s
.PHONY : srv/test_g/gradient_strip.cpp.s

srv/test_g/main.o: srv/test_g/main.cpp.o
.PHONY : srv/test_g/main.o

# target to build an object file
srv/test_g/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/main.cpp.o
.PHONY : srv/test_g/main.cpp.o

srv/test_g/main.i: srv/test_g/main.cpp.i
.PHONY : srv/test_g/main.i

# target to preprocess a source file
srv/test_g/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/main.cpp.i
.PHONY : srv/test_g/main.cpp.i

srv/test_g/main.s: srv/test_g/main.cpp.s
.PHONY : srv/test_g/main.s

# target to generate assembly for a file
srv/test_g/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CalculateDragAndDrop.dir/build.make CMakeFiles/CalculateDragAndDrop.dir/srv/test_g/main.cpp.s
.PHONY : srv/test_g/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CalculateDragAndDrop_autogen"
	@echo "... CalculateDragAndDrop_autogen_timestamp_deps"
	@echo "... CalculateDragAndDrop"
	@echo "... CalculateDragAndDrop_autogen/mocs_compilation.o"
	@echo "... CalculateDragAndDrop_autogen/mocs_compilation.i"
	@echo "... CalculateDragAndDrop_autogen/mocs_compilation.s"
	@echo "... srv/UI/Application/Application.o"
	@echo "... srv/UI/Application/Application.i"
	@echo "... srv/UI/Application/Application.s"
	@echo "... srv/UI/Button/Button.o"
	@echo "... srv/UI/Button/Button.i"
	@echo "... srv/UI/Button/Button.s"
	@echo "... srv/UI/CreateHistory/CreateHistory.o"
	@echo "... srv/UI/CreateHistory/CreateHistory.i"
	@echo "... srv/UI/CreateHistory/CreateHistory.s"
	@echo "... srv/UI/Window/Window.o"
	@echo "... srv/UI/Window/Window.i"
	@echo "... srv/UI/Window/Window.s"
	@echo "... srv/main.o"
	@echo "... srv/main.i"
	@echo "... srv/main.s"
	@echo "... srv/test_f/alphaslider.o"
	@echo "... srv/test_f/alphaslider.i"
	@echo "... srv/test_f/alphaslider.s"
	@echo "... srv/test_f/colorpicker.o"
	@echo "... srv/test_f/colorpicker.i"
	@echo "... srv/test_f/colorpicker.s"
	@echo "... srv/test_f/hueslider.o"
	@echo "... srv/test_f/hueslider.i"
	@echo "... srv/test_f/hueslider.s"
	@echo "... srv/test_f/main.o"
	@echo "... srv/test_f/main.i"
	@echo "... srv/test_f/main.s"
	@echo "... srv/test_g/gradientSettings.o"
	@echo "... srv/test_g/gradientSettings.i"
	@echo "... srv/test_g/gradientSettings.s"
	@echo "... srv/test_g/gradient_editor.o"
	@echo "... srv/test_g/gradient_editor.i"
	@echo "... srv/test_g/gradient_editor.s"
	@echo "... srv/test_g/gradient_strip.o"
	@echo "... srv/test_g/gradient_strip.i"
	@echo "... srv/test_g/gradient_strip.s"
	@echo "... srv/test_g/main.o"
	@echo "... srv/test_g/main.i"
	@echo "... srv/test_g/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

